apiVersion: servicefunctionchain.polito.it/v1
kind: ServiceFunctionChain
metadata:
  name: sfc1
spec:
  targetNodeName: kind-worker #Change node name
  networkFunctions:
    - name: client
      links:
        firewall: eth1

    - name: firewall
      links:
        client: eth1
        gw: eth2

    - name: gw
      links:
        firewall: eth1
